name: Deploy on push
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: [self-hosted, policy]
    env:
      GIT_SSH_COMMAND: 'ssh -i /root/.ssh/policy_runner -o StrictHostKeyChecking=yes'
    steps:
      - name: Ensure repo exists (clone if missing)
        run: |
          set -euxo pipefail
          git config --global --add safe.directory /var/www/html/policy
          if [ ! -d /var/www/html/policy/.git ]; then
            rm -rf /var/www/html/policy
            git clone git@github.com:vuchungbt/policy.git /var/www/html/policy
          fi
      - name: Deploy
        run: |
          set -euxo pipefail
          cd /var/www/html/policy
          git fetch --all
          git checkout -f main
          git reset --hard origin/main
          echo "Deployed"
